### ISSUE TITLE
sambamba depth window sementation fault [core dump] using --combined flag

### ISSUE THREAD

**Issue by iamh2o** [biod/sambamba#395] opened 2019-04-27 07:18 UTC
* version of  sambamba == 0.6.8

* version of samtools if the issue is with pileup tool = N/A

* the command line or bash script used (feel free to shorten paths and filenames)
> sambamba depth window --combined  -w 1000 -c 0 -q=30 -m ./A.bam ./B.bam

Outputs:
sambamba 0.6.8 by Artem Tarasov and Pjotr Prins (C) 2012-2018
    LDC 1.13.0 / DMD v2.083.1 / LLVM7.0.1 / bootstrap LDC - the LLVM D compiler (0.17.6)

\# chrom	chromStart	chromEnd	readCount	meanCoverage
Processing reference #1 (chr1)
chr1	9000	10000	12	0.014
Segmentation fault (core dumped)

The --combined flag is causing the problem here. When it is removed, the tool executes normally.

* whenever possible, a set of BAM/BED files to reproduce the issue
I am using a 40x coverage WGS NA12878 BAM and a 40x WGS NA24385 BAM.  Too large to include.  The problem does not present when I test small BAMs however.

**Comment by pjotrp** [comment] 2019-04-28 14:52
Can you try 0.6.6 and see if it does the same? May be a duplicate of #394

**Closed** 2019-05-29 14:43 UTC
Labels: waiting for response

**Comment by QichenFU** [comment] 2022-07-12 13:42
Hi, I have the same problem and it cannot be solved by 0.6.6. 

sambamba version: 0.6.6
Command: sambamba depth region -t 8 -L units.bed sorted_Pooled_cis.bam

output: 
# chrom	chromStart	chromEnd	F3	F4	readCount	meanCoverage	sampleName
Segmentation fault (core dumped)

bed file (part): 

chrI	37	537	chrI:37-537|bin	500
chrI	612	1112	chrI:612-1112|bin	500
chrI	1187	1687	chrI:1187-1687|bin	500
chrI	1725	2225	chrI:1725-2225|putative_enhancer	500
chrI	2225	2688	chrI:2225-2688|bin	463
chrI	2688	3188	chrI:2688-3188|bin	500
chrI	3188	3651	chrI:3188-3651|bin	463
chrI	3651	4126	chrI:3651-4126|non-coding_promoter	475
chrI	4126	4601	chrI:4126-4601|putative_enhancer	475
chrI	4601	5099	chrI:4601-5099|bin	498
chrI	5099	5599	chrI:5099-5599|bin	500
chrI	5599	6099	chrI:5599-6099|bin	500
