### ISSUE TITLE
core dump sambamba depth

### ISSUE THREAD

**Issue by aderzelle** [biod/sambamba#408] opened 2019-09-10 20:59 UTC
Hello,
I am using sambamba 0.7.0 and get the following error:

`./mapping.sh: line 32:  8447 Segmentation fault      (core dumped) ./sambamba-0.7.0-linux-static depth window -w 20000 -T 0 -t $threads -F 'mapping_quality >= 0' $out.sorted.bam > $out.cov`

It only happens with one of my bam file. I don't understand what this file has that is peculiar. It's 22 Gb long, I could try to send it through wetransfer.
I have tried several versions of sambamba. 
Any suggestion? thank you 
EDIT: I solved the problem by using 20 threads instead of 48 ...

**Comment by aderzelle** [comment] 2019-09-16 11:01
Hello again, 
actually this issue shows up quite regularly and when it happens I have to try different values of threads until there is no more core dumps.

**Comment by pjotrp** [comment] 2019-09-16 13:49
You mean with different BAM files?

**Comment by aderzelle** [comment] 2019-09-16 13:52
yes with different bam files. 
Note that I am not able to reproduce the problem on different computers, so it might be related to the CPU. The core dump happens regularly with a 
Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
While so far I haven't experienced it on my laptop running with a
Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz

**Comment by pjotrp** [comment] 2019-09-16 14:04
Yeah, that is a hardware problem. Good on you to figure it out :)

Duplicate of https://github.com/biod/sambamba/issues/335

**Closed by pjotrp** 2019-09-16 14:04 UTC
