### ISSUE TITLE
Segmentation fault (core dumped) when viewing .bam

### ISSUE THREAD

**Issue by TracyBallinger** [biod/sambamba#186] opened 2015-12-22 09:56 UTC
I'm getting a segmentation fault with sambamba_v0.5.9 on linux.  The following command works in that it generates the correct output, but there is a segmentation fault at the end which disrupts piping the output into something else.  

sambamba_v0.5.9 view -S tmpsmall.sam > tmp2.sam

This seems to happen with any view command (viewing a .bam file, too).
Let me know if you'd like the example file or anything else from me.  
Thanks!

**Comment by lomereiter** [comment] 2016-01-01 21:54
Hi, are you able to observe this bug with previous versions?

**Comment by TracyBallinger** [comment] 2016-01-05 09:17
Yes, I am.  I checked v5.8, v5.7, and v5.1, and they all give a seg fault
after they run.  Thanks if you have any ideas about what's amiss.

**Comment by lomereiter** [comment] 2016-01-06 21:10
Thanks for the testing. Can you reproduce the bug on another machine? Which version of glibc is installed? (`ldd --version`)

**Comment by TracyBallinger** [comment] 2016-01-07 09:14
I tested it on another machine and did not have any problems.  That machine
has glibc 2.5.  The machine that gives a seg fault has glibc 2.17.

**Comment by lomereiter** [comment] 2016-01-07 18:58
Ok, what distro are you using? (so I could try to reproduce it in Docker/VM)

**Comment by TracyBallinger** [comment] 2016-01-08 08:46
It's this version:

$ cat /proc/version

Linux version 3.10.0-229.14.1.el7.x86_64 (mockbuild@sl7-uefisign.fnal.gov)
(gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Tue Sep 15
05:09:55 CDT 2015

**Comment by lomereiter** [comment] 2016-01-08 18:49
I installed SL7 virtual machine, but still can't reproduce the issue (the tiny difference in kernels could hardly account for that). So unfortunately I have no idea what could be wrong.

[vagrant@sl7-dev ~]$ cat /proc/version 
Linux version 3.10.0-229.20.1.el7.x86_64 (mockbuild@sl7-uefisign.fnal.gov) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Wed Nov 4 10:08:36 CST 2015
[vagrant@sl7-dev ~]$ ldd --version
ldd (GNU libc) 2.17

**Comment by wyleung** [comment] 2016-03-03 13:18
Sorry for hijacking this issue. I'm experiencing a similar issue.

Using `sambamba view -t 4 bamfile.bam`. A run on the system works fine.

However via a OGE cluster job, it throws:

```
[727524.532873] sambamba_v0.5.9[43566]: segfault at 7f7e87fff6f8 ip 0000000000567054 sp 00007fff68f8c7f0 error 4 in sambamba_v0.5.9[400000+1fa000]
[731173.418826] sambamba_v0.5.9[45719]: segfault at 7f320fd7c6f8 ip 0000000000567054 sp 00007fffef6a42b0 error 4 in sambamba_v0.5.9[400000+1fa000]
[773562.652610] sambamba_v0.5.9[18849]: segfault at 7f73e01306f8 ip 0000000000567054 sp 00007ffd9085a0c0 error 4 in sambamba_v0.5.9[400000+1fa000]
```

I don't know wheter this relates to the problem described above. I've backtraced this to that sambamba is hitting the memory limit somehow and fails consistantly on the 17th contig (viewing human chromosome) of any bamfile.

Under normal runs (without OGE/SGE jobs) this runs fine on the same compute nodes.

**Comment by TracyBallinger** [comment] 2016-03-03 15:25
Yes, I figured out that the problem was that it was hitting the stack
limit.  My fix has been to just request more memory when submitting it as a
job.

**Comment by wyleung** [comment] 2016-03-04 09:44
:) nice.. I was on that also yesterday. 

For the SGE users, change the "-l h_stack=64M" to a higher number if you run into problem running sambamba.

ref; http://www.softpanorama.org/HPC/Grid_engine/Troubleshooting/index.shtml

**Comment by wyleung** [comment] 2016-03-11 12:22
@lomereiter I think this is an issue that has been solved. This is a platform specific issue (running with OGE/SGE setup)

@TracyBallinger could you confirm this?

**Comment by TracyBallinger** [comment] 2016-03-11 16:56
Yes, that is correct.

**Comment by lomereiter** [comment] 2016-03-11 18:11
Many thanks for resolving this!

**Comment by stevekm** [comment] 2018-10-11 17:30
I am getting the same error on my system using `sambamba flagstat`. We have SLURM installed. When I submit the command under a compute job, it goes straight to the "segmentation fault" error with an error code of 139. If I run it interactively on the head no (no job submission), the command actually gives the exepected output; *then* gives a seg fault:
```
kellys04@bigpurple-ln1:/gpfs/data/test$ sambamba flagstat NTC-1-H2O.bam; echo $?
881 + 0 in total (QC-passed reads + QC-failed reads)
1 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
881 + 0 mapped (100.00%:N/A)
880 + 0 paired in sequencing
440 + 0 read1
440 + 0 read2
872 + 0 properly paired (99.09%:N/A)
880 + 0 with itself and mate mapped
0 + 0 singletons (0.00%:N/A)
8 + 0 with mate mapped to a different chr
8 + 0 with mate mapped to a different chr (mapQ>=5)
/bin/bash: line 1: 371308 Segmentation fault      sambamba flagstat NTC-1-H2O.bam
139
```

I saw some mentioning of "stack size" in the SLURM docs [here](https://slurm.schedmd.com/slurm.conf.html) and [here](https://slurm.schedmd.com/sbatch.html) but they do not give clear instructions on how to adjust them, and the fact that the error occurs without involving SLURM suggests that maybe its not related to the scheduler. 

Some other info:

- running RHEL 7

- sambamba 0.6.6

```
$ cat /proc/version
Linux version 3.10.0-693.17.1.el7.x86_64 (mockbuild@x86-041.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Sun Jan 14 10:36:03 EST 2018

$ ldd --version
ldd (GNU libc) 2.17

$ ulimit
unlimited
```

And the error happens as well when running sambamba from a `conda` installation, and when running it from inside a Singularity container.

**Comment by stevekm** [comment] 2018-10-12 17:53
I tried it with 0.6.8 (also from conda), and it works, no errors. 
Unfortunately, our pipeline requires the use of 0.6.6. I guess if this is a bug in the program and not something that we can fix by adjusting our system, I will just have to review our software versioning protocol and try to get it updated. Thanks.

**Comment by pjotrp** [comment] 2018-10-12 18:07
Excellent. Thanks for reporting. Latest sambamba is 20% faster too.

**Closed by pjotrp** 2018-10-12 18:07 UTC
Labels: bug, help wanted
